/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/admin/stats": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Stats */
    get: operations["get_stats_admin_stats_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/admin/users": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Users */
    get: operations["list_users_admin_users_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/admin/leagues": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Leagues */
    get: operations["list_leagues_admin_leagues_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/admin/scripts": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Scripts */
    get: operations["list_scripts_admin_scripts_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/admin/scripts/compile": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Compile Script */
    post: operations["compile_script_admin_scripts_compile_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health */
    get: operations["health_health_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/scripts": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Scripts
     * @description List all successfully compiled season scripts available for session creation.
     */
    get: operations["list_scripts_scripts_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/scripts/{script_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Script */
    get: operations["get_script_scripts__script_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/register": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Register */
    post: operations["register_auth_register_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Auth0 Login */
    get: operations["auth0_login_auth_login_get"];
    put?: never;
    /** Login */
    post: operations["login_auth_login_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/callback": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Auth0 Callback */
    get: operations["auth0_callback_auth_callback_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Me */
    get: operations["me_auth_me_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/me/api-key": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /**
     * Upsert Api Key
     * @description Store or replace the user's API key for the given provider.
     */
    put: operations["upsert_api_key_auth_me_api_key_put"];
    post?: never;
    /**
     * Delete Api Key
     * @description Remove the user's API key for the given provider.
     */
    delete: operations["delete_api_key_auth_me_api_key_delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/leagues": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Leagues */
    get: operations["list_leagues_leagues_get"];
    put?: never;
    /** Create League */
    post: operations["create_league_leagues_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/leagues/{league_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get League */
    get: operations["get_league_leagues__league_id__get"];
    put?: never;
    post?: never;
    /** Delete League */
    delete: operations["delete_league_leagues__league_id__delete"];
    options?: never;
    head?: never;
    /** Update League */
    patch: operations["update_league_leagues__league_id__patch"];
    trace?: never;
  };
  "/leagues/{league_id}/members": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Members */
    get: operations["list_members_leagues__league_id__members_get"];
    put?: never;
    /** Add Member */
    post: operations["add_member_leagues__league_id__members_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/leagues/{league_id}/members/{user_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Remove Member */
    delete: operations["remove_member_leagues__league_id__members__user_id__delete"];
    options?: never;
    head?: never;
    /** Change Member Role */
    patch: operations["change_member_role_leagues__league_id__members__user_id__patch"];
    trace?: never;
  };
  "/leagues/{league_id}/members/me/leave": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Leave League */
    post: operations["leave_league_leagues__league_id__members_me_leave_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/leagues/{league_id}/invites": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Invites */
    get: operations["list_invites_leagues__league_id__invites_get"];
    put?: never;
    /** Create Invite */
    post: operations["create_invite_leagues__league_id__invites_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/leagues/join/{token}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Join League */
    post: operations["join_league_leagues_join__token__post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/leagues/{league_id}/sessions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Sessions
     * @description List all sessions belonging to this league, newest first.
     */
    get: operations["list_sessions_leagues__league_id__sessions_get"];
    put?: never;
    /** Create Session */
    post: operations["create_session_leagues__league_id__sessions_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/leagues/{league_id}/api-key": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get League Api Key Status
     * @description Return which providers have a league key set. Manager-only.
     */
    get: operations["get_league_api_key_status_leagues__league_id__api_key_get"];
    /**
     * Set League Api Key
     * @description Upsert an encrypted API key for the given provider. Manager-only.
     */
    put: operations["set_league_api_key_leagues__league_id__api_key_put"];
    post?: never;
    /**
     * Delete League Api Key
     * @description Remove the league key for a given provider. Manager-only.
     */
    delete: operations["delete_league_api_key_leagues__league_id__api_key_delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/users/search": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Search Users */
    get: operations["search_users_users_search_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/sessions/{session_id}/join": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Join Session */
    post: operations["join_session_sessions__session_id__join_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/sessions/{session_id}/leave": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Leave Session */
    post: operations["leave_session_sessions__session_id__leave_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/sessions/{session_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Session */
    get: operations["get_session_sessions__session_id__get"];
    put?: never;
    post?: never;
    /**
     * Delete Session
     * @description Delete a session. Only the session owner or a league manager may do this.
     *     Running sessions are paused first.
     */
    delete: operations["delete_session_sessions__session_id__delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/sessions/{session_id}/start": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Start Session
     * @description Start (or resume) the EventRunner for a session.
     *
     *     Allowed statuses: DRAFT_PENDING, PAUSED, IN_PROGRESS (idempotent resume).
     *     Only the session owner may start it.
     */
    post: operations["start_session_sessions__session_id__start_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/sessions/{session_id}/pause": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Pause Session
     * @description Pause a running session. Only the owner may pause it.
     */
    post: operations["pause_session_sessions__session_id__pause_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/sessions/{session_id}/scores": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Session Scores
     * @description Return matchup scores for a given week (defaults to current week).
     *     Includes per-player breakdowns for both sides of each matchup.
     */
    get: operations["get_session_scores_sessions__session_id__scores_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/sessions/{session_id}/standings": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Session Standings
     * @description Return current season standings, ranked by wins then points_for.
     */
    get: operations["get_session_standings_sessions__session_id__standings_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/sessions/{session_id}/decisions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Session Decisions
     * @description Return recent agent decisions, newest first.
     *     Optionally filter to a specific team with ?team_id=<uuid>.
     */
    get: operations["get_session_decisions_sessions__session_id__decisions_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/sessions/{session_id}/trades": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Trades
     * @description List all trades in a session. Must be a session member.
     */
    get: operations["list_trades_sessions__session_id__trades_get"];
    put?: never;
    /**
     * Propose Trade
     * @description Propose a trade. Acquires soft locks on all involved players.
     */
    post: operations["propose_trade_sessions__session_id__trades_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/trades/{trade_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Trade */
    get: operations["get_trade_trades__trade_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/trades/{trade_id}/respond": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Respond To Trade
     * @description Accept or reject a trade proposal. Only the receiving team can respond.
     */
    post: operations["respond_to_trade_trades__trade_id__respond_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/trades/{trade_id}/cancel": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Cancel Trade
     * @description Cancel a pending trade. Only the proposing team can cancel.
     */
    post: operations["cancel_trade_trades__trade_id__cancel_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Root */
    get: operations["root__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** AddMemberRequest */
    AddMemberRequest: {
      /**
       * User Id
       * Format: uuid
       */
      user_id: string;
    };
    /** AdminLeagueResponse */
    AdminLeagueResponse: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Name */
      name: string;
      /**
       * Created By
       * Format: uuid
       */
      created_by: string;
      /** Member Count */
      member_count: number;
      /** Session Count */
      session_count: number;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /** AdminScriptResponse */
    AdminScriptResponse: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Sport */
      sport: string;
      /** Season */
      season: number;
      /** Season Type */
      season_type: string;
      /** Status */
      status: string;
      /** Total Events */
      total_events: number;
      /** Compiled At */
      compiled_at: string | null;
    };
    /** AdminStatsResponse */
    AdminStatsResponse: {
      /** User Count */
      user_count: number;
      /** League Count */
      league_count: number;
      /** Session Count */
      session_count: number;
      /** Script Count */
      script_count: number;
    };
    /** AdminUserResponse */
    AdminUserResponse: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Email */
      email: string;
      /** Display Name */
      display_name: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /** ApiKeyDeleteRequest */
    ApiKeyDeleteRequest: {
      provider: components["schemas"]["LLMProvider"];
    };
    /** ApiKeyRequest */
    ApiKeyRequest: {
      provider: components["schemas"]["LLMProvider"];
      /** Key */
      key: string;
    };
    /** ChangeMemberRoleRequest */
    ChangeMemberRoleRequest: {
      role: components["schemas"]["LeagueMembershipRole"];
    };
    /** CompileRequest */
    CompileRequest: {
      /**
       * Sport
       * @default nfl
       */
      sport: string;
      /**
       * Season
       * @default 2025
       */
      season: number;
      /**
       * Season Type
       * @default regular
       */
      season_type: string;
      /**
       * Force
       * @default false
       */
      force: boolean;
    };
    /** CompileResponse */
    CompileResponse: {
      /**
       * Script Id
       * Format: uuid
       */
      script_id: string;
      /** Status */
      status: string;
      /** Message */
      message: string;
    };
    /** DecisionEntry */
    DecisionEntry: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Team Id
       * Format: uuid
       */
      team_id: string;
      /** Team Name */
      team_name: string;
      /** Seq */
      seq: number;
      /** Decision Type */
      decision_type: string;
      /** Payload */
      payload: {
        [key: string]: unknown;
      };
      /** Reasoning Trace */
      reasoning_trace: {
        [key: string]: unknown;
      } | null;
      /** Triggered By */
      triggered_by: unknown[];
      /** Tokens Used */
      tokens_used: number;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /** DecisionsResponse */
    DecisionsResponse: {
      /** Decisions */
      decisions: components["schemas"]["DecisionEntry"][];
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** InviteByEmailRequest */
    InviteByEmailRequest: {
      /** Email */
      email?: string | null;
      /**
       * Expires Hours
       * @default 72
       */
      expires_hours: number;
    };
    /** InviteResponse */
    InviteResponse: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Token */
      token: string;
      /** Invited Email */
      invited_email: string | null;
      status: components["schemas"]["LeagueInviteStatus"];
      /**
       * Expires At
       * Format: date-time
       */
      expires_at: string;
      /** Accept Url */
      accept_url: string;
    };
    /** JoinSessionResponse */
    JoinSessionResponse: {
      /**
       * Session Id
       * Format: uuid
       */
      session_id: string;
      /**
       * Team Id
       * Format: uuid
       */
      team_id: string;
      /** Message */
      message: string;
    };
    /**
     * LLMProvider
     * @enum {string}
     */
    LLMProvider: "anthropic" | "openai" | "gemini";
    /** LeagueApiKeyDeleteRequest */
    LeagueApiKeyDeleteRequest: {
      provider: components["schemas"]["LLMProvider"];
    };
    /** LeagueApiKeyRequest */
    LeagueApiKeyRequest: {
      provider: components["schemas"]["LLMProvider"];
      /** Api Key */
      api_key: string;
    };
    /** LeagueApiKeyStatusResponse */
    LeagueApiKeyStatusResponse: {
      /** Has Keys */
      has_keys: {
        [key: string]: boolean;
      };
    };
    /** LeagueCreate */
    LeagueCreate: {
      /** Name */
      name: string;
      /** @default manager_only */
      session_creation: components["schemas"]["SessionCreationPolicy"];
      /**
       * Max Members
       * @default 100
       */
      max_members: number;
      /**
       * Allow Shared Key
       * @default false
       */
      allow_shared_key: boolean;
    };
    /**
     * LeagueInviteStatus
     * @enum {string}
     */
    LeagueInviteStatus: "pending" | "accepted" | "declined" | "expired";
    /**
     * LeagueMembershipRole
     * @enum {string}
     */
    LeagueMembershipRole: "manager" | "member";
    /**
     * LeagueMembershipStatus
     * @enum {string}
     */
    LeagueMembershipStatus: "active" | "left" | "removed";
    /** LeagueResponse */
    LeagueResponse: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Name */
      name: string;
      /**
       * Created By
       * Format: uuid
       */
      created_by: string;
      session_creation: components["schemas"]["SessionCreationPolicy"];
      /** Max Members */
      max_members: number;
      /** Is Auto Generated */
      is_auto_generated: boolean;
      /** Allow Shared Key */
      allow_shared_key: boolean;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Member Count */
      member_count: number;
      /**
       * Has League Keys
       * @default {}
       */
      has_league_keys: {
        [key: string]: boolean;
      };
      /** My Role */
      my_role?: string | null;
    };
    /** LeagueUpdate */
    LeagueUpdate: {
      /** Name */
      name?: string | null;
      session_creation?: components["schemas"]["SessionCreationPolicy"] | null;
      /** Allow Shared Key */
      allow_shared_key?: boolean | null;
    };
    /** LoginRequest */
    LoginRequest: {
      /**
       * Email
       * Format: email
       */
      email: string;
      /** Password */
      password: string;
    };
    /** MatchupScoreResponse */
    MatchupScoreResponse: {
      /**
       * Matchup Id
       * Format: uuid
       */
      matchup_id: string;
      /** Period Number */
      period_number: number;
      /**
       * Home Team Id
       * Format: uuid
       */
      home_team_id: string;
      /** Home Team Name */
      home_team_name: string;
      /** Home Score */
      home_score: number;
      /**
       * Away Team Id
       * Format: uuid
       */
      away_team_id: string;
      /** Away Team Name */
      away_team_name: string;
      /** Away Score */
      away_score: number;
      /** Winner Team Id */
      winner_team_id: string | null;
      /** Home Players */
      home_players: components["schemas"]["PlayerScoreItem"][];
      /** Away Players */
      away_players: components["schemas"]["PlayerScoreItem"][];
    };
    /** MemberResponse */
    MemberResponse: {
      /**
       * User Id
       * Format: uuid
       */
      user_id: string;
      /** Display Name */
      display_name: string;
      /** Email */
      email: string;
      role: components["schemas"]["LeagueMembershipRole"];
      status: components["schemas"]["LeagueMembershipStatus"];
      /**
       * Joined At
       * Format: date-time
       */
      joined_at: string;
    };
    /** PlayerScoreItem */
    PlayerScoreItem: {
      /** Player Id */
      player_id: string;
      /** Points Total */
      points_total: number;
      /** Stats Json */
      stats_json: {
        [key: string]: unknown;
      };
    };
    /**
     * PriorityReset
     * @enum {string}
     */
    PriorityReset: "rolling" | "season_long" | "weekly_standings";
    /** ProposeTradeRequest */
    ProposeTradeRequest: {
      /**
       * Receiving Team Id
       * Format: uuid
       */
      receiving_team_id: string;
      /** Offered Player Ids */
      offered_player_ids: string[];
      /** Requested Player Ids */
      requested_player_ids: string[];
      /** Note */
      note?: string | null;
      /**
       * Expires Hours
       * @default 48
       */
      expires_hours: number;
    };
    /** RegisterRequest */
    RegisterRequest: {
      /**
       * Email
       * Format: email
       */
      email: string;
      /** Password */
      password: string;
      /** Display Name */
      display_name: string;
    };
    /** RespondTradeRequest */
    RespondTradeRequest: {
      /** Accept */
      accept: boolean;
    };
    /** ScriptResponse */
    ScriptResponse: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Sport */
      sport: string;
      /** Season */
      season: number;
      /** Season Type */
      season_type: string;
      /** Total Events */
      total_events: number;
      /** Total Sim Hours */
      total_sim_hours: number;
      /** Status */
      status: string;
      /** Compiled At */
      compiled_at: string | null;
    };
    /**
     * ScriptSpeed
     * @enum {string}
     */
    ScriptSpeed: "blitz" | "managed" | "immersive";
    /** ScriptSummary */
    ScriptSummary: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Sport */
      sport: string;
      /** Season */
      season: number;
      /** Season Type */
      season_type: string;
      /** Total Events */
      total_events: number;
    };
    /** SessionCreate */
    SessionCreate: {
      /** Name */
      name: string;
      /**
       * Script Id
       * Format: uuid
       */
      script_id: string;
      /** Sport */
      sport: string;
      /** Season */
      season: number;
      script_speed: components["schemas"]["ScriptSpeed"];
      /** @default faab */
      waiver_mode: components["schemas"]["WaiverMode"];
      priority_reset?: components["schemas"]["PriorityReset"] | null;
      /** Compression Factor */
      compression_factor?: number | null;
      /**
       * Max Teams
       * @default 12
       */
      max_teams: number;
      /**
       * Scoring Config
       * @default {}
       */
      scoring_config: {
        [key: string]: unknown;
      };
    };
    /**
     * SessionCreationPolicy
     * @enum {string}
     */
    SessionCreationPolicy: "manager_only" | "any_member";
    /** SessionDetailResponse */
    SessionDetailResponse: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Name */
      name: string;
      /** Sport */
      sport: string;
      /** Season */
      season: number;
      /** Status */
      status: string;
      /** Script Speed */
      script_speed: string;
      /** Waiver Mode */
      waiver_mode: string;
      /** Current Seq */
      current_seq: number;
      /** Current Week */
      current_week: number;
      /** Is Running */
      is_running: boolean;
      script: components["schemas"]["ScriptSummary"];
      /** Teams */
      teams: components["schemas"]["TeamSummary"][];
      /** League Id */
      league_id: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /** SessionResponse */
    SessionResponse: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Name */
      name: string;
      /** Sport */
      sport: string;
      /** Season */
      season: number;
      /** Status */
      status: string;
      script_speed: components["schemas"]["ScriptSpeed"];
      waiver_mode: components["schemas"]["WaiverMode"];
      /** Max Teams */
      max_teams: number;
      /** League Id */
      league_id: string | null;
      /**
       * Owner Id
       * Format: uuid
       */
      owner_id: string;
      /** Team Id */
      team_id?: string | null;
      /**
       * Current Teams
       * @default 0
       */
      current_teams: number;
      /**
       * Current Week
       * @default 0
       */
      current_week: number;
    };
    /** StandingsEntry */
    StandingsEntry: {
      /** Rank */
      rank: number;
      /**
       * Team Id
       * Format: uuid
       */
      team_id: string;
      /** Team Name */
      team_name: string;
      /** Team Type */
      team_type: string;
      /** Wins */
      wins: number;
      /** Losses */
      losses: number;
      /** Ties */
      ties: number;
      /** Points For */
      points_for: number;
      /** Points Against */
      points_against: number;
    };
    /** StandingsResponse */
    StandingsResponse: {
      /** Standings */
      standings: components["schemas"]["StandingsEntry"][];
    };
    /** TeamSummary */
    TeamSummary: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Name */
      name: string;
      /** Type */
      type: string;
      /** Faab Balance */
      faab_balance: number;
    };
    /** TokenResponse */
    TokenResponse: {
      /** Access Token */
      access_token: string;
      /**
       * Token Type
       * @default bearer
       */
      token_type: string;
    };
    /** TradeLockInfo */
    TradeLockInfo: {
      /** Player Id */
      player_id: string;
      /**
       * Locked Until
       * Format: date-time
       */
      locked_until: string;
    };
    /** TradeResponse */
    TradeResponse: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Session Id
       * Format: uuid
       */
      session_id: string;
      /**
       * Proposing Team Id
       * Format: uuid
       */
      proposing_team_id: string;
      /**
       * Receiving Team Id
       * Format: uuid
       */
      receiving_team_id: string;
      /** Offered Player Ids */
      offered_player_ids: string[];
      /** Requested Player Ids */
      requested_player_ids: string[];
      status: components["schemas"]["TradeStatus"];
      /** Note */
      note: string | null;
      /**
       * Proposed At
       * Format: date-time
       */
      proposed_at: string;
      /** Resolved At */
      resolved_at: string | null;
      /** Locks */
      locks: components["schemas"]["TradeLockInfo"][];
    };
    /**
     * TradeStatus
     * @enum {string}
     */
    TradeStatus: "pending" | "accepted" | "rejected" | "expired" | "cancelled";
    /** UserResponse */
    UserResponse: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Email */
      email: string;
      /** Display Name */
      display_name: string;
      /** Has Keys */
      has_keys: {
        [key: string]: boolean;
      };
    };
    /** UserSearchResult */
    UserSearchResult: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Email */
      email: string;
      /** Display Name */
      display_name: string;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
    /**
     * WaiverMode
     * @enum {string}
     */
    WaiverMode: "faab" | "priority";
    /** WeekScoresResponse */
    WeekScoresResponse: {
      /** Week */
      week: number;
      /** Matchups */
      matchups: components["schemas"]["MatchupScoreResponse"][];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  get_stats_admin_stats_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AdminStatsResponse"];
        };
      };
    };
  };
  list_users_admin_users_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AdminUserResponse"][];
        };
      };
    };
  };
  list_leagues_admin_leagues_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AdminLeagueResponse"][];
        };
      };
    };
  };
  list_scripts_admin_scripts_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AdminScriptResponse"][];
        };
      };
    };
  };
  compile_script_admin_scripts_compile_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CompileRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CompileResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  health_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  list_scripts_scripts_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ScriptResponse"][];
        };
      };
    };
  };
  get_script_scripts__script_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        script_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ScriptResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  register_auth_register_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RegisterRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TokenResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  auth0_login_auth_login_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  login_auth_login_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TokenResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  auth0_callback_auth_callback_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  me_auth_me_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UserResponse"];
        };
      };
    };
  };
  upsert_api_key_auth_me_api_key_put: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ApiKeyRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_api_key_auth_me_api_key_delete: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ApiKeyDeleteRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_leagues_leagues_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LeagueResponse"][];
        };
      };
    };
  };
  create_league_leagues_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LeagueCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LeagueResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_league_leagues__league_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        league_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LeagueResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_league_leagues__league_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        league_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_league_leagues__league_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        league_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LeagueUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LeagueResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_members_leagues__league_id__members_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        league_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MemberResponse"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  add_member_leagues__league_id__members_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        league_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AddMemberRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MemberResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  remove_member_leagues__league_id__members__user_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        league_id: string;
        user_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  change_member_role_leagues__league_id__members__user_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        league_id: string;
        user_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ChangeMemberRoleRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MemberResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  leave_league_leagues__league_id__members_me_leave_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        league_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_invites_leagues__league_id__invites_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        league_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["InviteResponse"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_invite_leagues__league_id__invites_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        league_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["InviteByEmailRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["InviteResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  join_league_leagues_join__token__post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        token: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LeagueResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_sessions_leagues__league_id__sessions_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        league_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SessionResponse"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_session_leagues__league_id__sessions_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        league_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SessionCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SessionResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_league_api_key_status_leagues__league_id__api_key_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        league_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LeagueApiKeyStatusResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  set_league_api_key_leagues__league_id__api_key_put: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        league_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LeagueApiKeyRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_league_api_key_leagues__league_id__api_key_delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        league_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LeagueApiKeyDeleteRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  search_users_users_search_get: {
    parameters: {
      query: {
        q: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UserSearchResult"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  join_session_sessions__session_id__join_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        session_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["JoinSessionResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  leave_session_sessions__session_id__leave_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        session_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_session_sessions__session_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        session_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SessionDetailResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_session_sessions__session_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        session_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  start_session_sessions__session_id__start_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        session_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SessionDetailResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  pause_session_sessions__session_id__pause_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        session_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SessionDetailResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_session_scores_sessions__session_id__scores_get: {
    parameters: {
      query?: {
        week?: number | null;
      };
      header?: never;
      path: {
        session_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["WeekScoresResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_session_standings_sessions__session_id__standings_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        session_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StandingsResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_session_decisions_sessions__session_id__decisions_get: {
    parameters: {
      query?: {
        limit?: number;
        team_id?: string | null;
      };
      header?: never;
      path: {
        session_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DecisionsResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_trades_sessions__session_id__trades_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        session_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TradeResponse"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  propose_trade_sessions__session_id__trades_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        session_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProposeTradeRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TradeResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_trade_trades__trade_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        trade_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TradeResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  respond_to_trade_trades__trade_id__respond_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        trade_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RespondTradeRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TradeResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  cancel_trade_trades__trade_id__cancel_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        trade_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  root__get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
    };
  };
}
