"""initial schema

Revision ID: 404ee19d7507
Revises:
Create Date: 2026-03-07 03:02:17.874327

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "404ee19d7507"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "season_scripts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "sport", sa.Enum("NFL", "NBA", "MLB", name="sport", native_enum=False), nullable=False
        ),
        sa.Column("season", sa.Integer(), nullable=False),
        sa.Column(
            "season_type",
            sa.Enum("PRESEASON", "REGULAR", "PLAYOFF", name="seasontype", native_enum=False),
            nullable=False,
        ),
        sa.Column("compiled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("total_events", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "COMPILED", "FAILED", name="scriptstatus", native_enum=False),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "sport", "season", "season_type", name="uq_season_scripts_sport_season_type"
        ),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=True),
        sa.Column("auth0_sub", sa.String(length=255), nullable=True),
        sa.Column("display_name", sa.String(length=100), nullable=False),
        sa.Column("anthropic_api_key_enc", sa.LargeBinary(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_auth0_sub"), "users", ["auth0_sub"], unique=False)
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "season_events",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("script_id", sa.UUID(), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("event_type", sa.String(length=50), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("week_number", sa.Integer(), nullable=False),
        sa.Column("sim_offset_hours", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["script_id"],
            ["season_scripts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_season_events_script_seq", "season_events", ["script_id", "seq"], unique=False
    )
    op.create_index(
        "ix_season_events_script_week", "season_events", ["script_id", "week_number"], unique=False
    )
    op.create_index("ix_season_events_type", "season_events", ["event_type"], unique=False)
    op.create_table(
        "sessions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("script_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column(
            "sport", sa.Enum("NFL", "NBA", "MLB", name="sport", native_enum=False), nullable=False
        ),
        sa.Column("season", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT_PENDING",
                "DRAFT_IN_PROGRESS",
                "DRAFT_COMPLETE",
                "IN_PROGRESS",
                "PAUSED",
                "COMPLETED",
                name="sessionstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "mode",
            sa.Enum("INSTANT", "COMPRESSED", "REALTIME", name="sessionmode", native_enum=False),
            nullable=False,
        ),
        sa.Column("compression_factor", sa.Integer(), nullable=True),
        sa.Column("wall_start_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("current_seq", sa.Integer(), nullable=False),
        sa.Column("scoring_config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["script_id"],
            ["season_scripts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "processed_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("event_type", sa.String(length=50), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "processed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_processed_events_session_seq", "processed_events", ["session_id", "seq"], unique=False
    )
    op.create_table(
        "session_invites",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("token", sa.String(length=128), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("used_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["used_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_session_invites_token"), "session_invites", ["token"], unique=True)
    op.create_table(
        "snapshots",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("period_number", sa.Integer(), nullable=False),
        sa.Column("world_state", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "taken_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_snapshots_session_seq", "snapshots", ["session_id", "seq"], unique=False)
    op.create_table(
        "teams",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column(
            "type",
            sa.Enum("AGENT", "HUMAN", "EXTERNAL", name="teamtype", native_enum=False),
            nullable=False,
        ),
        sa.Column("faab_balance", sa.Integer(), nullable=False),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "agent_decisions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("team_id", sa.UUID(), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column(
            "decision_type",
            sa.Enum(
                "LINEUP",
                "WAIVER",
                "TRADE_RESPONSE",
                "DRAFT_PICK",
                name="decisiontype",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("reasoning_trace", sa.Text(), nullable=True),
        sa.Column("tokens_used", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_agent_decisions_session_team",
        "agent_decisions",
        ["session_id", "team_id"],
        unique=False,
    )
    op.create_table(
        "drafts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column(
            "type", sa.Enum("SNAKE", "AUCTION", name="drafttype", native_enum=False), nullable=False
        ),
        sa.Column(
            "status",
            sa.Enum("PENDING", "IN_PROGRESS", "COMPLETED", name="draftstatus", native_enum=False),
            nullable=False,
        ),
        sa.Column("current_round", sa.Integer(), nullable=False),
        sa.Column("current_pick", sa.Integer(), nullable=False),
        sa.Column("turn_team_id", sa.UUID(), nullable=True),
        sa.Column("pick_deadline", sa.DateTime(timezone=True), nullable=True),
        sa.Column("auction_budget", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["turn_team_id"],
            ["teams.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("session_id"),
    )
    op.create_table(
        "matchups",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("period_number", sa.Integer(), nullable=False),
        sa.Column("home_team_id", sa.UUID(), nullable=False),
        sa.Column("away_team_id", sa.UUID(), nullable=False),
        sa.Column("home_score", sa.Float(), nullable=False),
        sa.Column("away_score", sa.Float(), nullable=False),
        sa.Column("winner_team_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["away_team_id"],
            ["teams.id"],
        ),
        sa.ForeignKeyConstraint(
            ["home_team_id"],
            ["teams.id"],
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["winner_team_id"],
            ["teams.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "session_id",
            "period_number",
            "home_team_id",
            "away_team_id",
            name="uq_matchup_period_teams",
        ),
    )
    op.create_index(
        "ix_matchups_session_period", "matchups", ["session_id", "period_number"], unique=False
    )
    op.create_table(
        "pending_decisions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("team_id", sa.UUID(), nullable=False),
        sa.Column(
            "decision_type",
            sa.Enum(
                "LINEUP",
                "WAIVER",
                "TRADE_RESPONSE",
                "DRAFT_PICK",
                name="decisiontype",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("context", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("deadline", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolution", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_pending_decisions_session_team",
        "pending_decisions",
        ["session_id", "team_id"],
        unique=False,
    )
    op.create_table(
        "player_scores",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("team_id", sa.UUID(), nullable=False),
        sa.Column("period_number", sa.Integer(), nullable=False),
        sa.Column("player_id", sa.String(length=50), nullable=False),
        sa.Column("points_total", sa.Float(), nullable=False),
        sa.Column("stats_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "session_id", "team_id", "period_number", "player_id", name="uq_player_score_period"
        ),
    )
    op.create_index(
        "ix_player_scores_session_period",
        "player_scores",
        ["session_id", "period_number"],
        unique=False,
    )
    op.create_table(
        "roster_players",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("team_id", sa.UUID(), nullable=False),
        sa.Column("player_id", sa.String(length=50), nullable=False),
        sa.Column(
            "slot",
            sa.Enum("ACTIVE", "BENCH", "IR", name="rosterslot", native_enum=False),
            nullable=False,
        ),
        sa.Column("acquired_week", sa.Integer(), nullable=False),
        sa.Column(
            "acquired_via",
            sa.Enum("DRAFT", "WAIVER", "TRADE", name="acquiredvia", native_enum=False),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("team_id", "player_id", name="uq_roster_team_player"),
    )
    op.create_index("ix_roster_players_team", "roster_players", ["team_id"], unique=False)
    op.create_table(
        "session_memberships",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column(
            "role",
            sa.Enum("OWNER", "MEMBER", "OBSERVER", name="membershiprole", native_enum=False),
            nullable=False,
        ),
        sa.Column("team_id", sa.UUID(), nullable=True),
        sa.Column(
            "joined_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("session_id", "user_id", name="uq_membership_session_user"),
    )
    op.create_table(
        "standings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("team_id", sa.UUID(), nullable=False),
        sa.Column("wins", sa.Integer(), nullable=False),
        sa.Column("losses", sa.Integer(), nullable=False),
        sa.Column("ties", sa.Integer(), nullable=False),
        sa.Column("points_for", sa.Float(), nullable=False),
        sa.Column("points_against", sa.Float(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("session_id", "team_id", name="uq_standings_session_team"),
    )
    op.create_table(
        "trade_proposals",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("proposing_team_id", sa.UUID(), nullable=False),
        sa.Column("receiving_team_id", sa.UUID(), nullable=False),
        sa.Column("offered_player_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("requested_player_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "ACCEPTED",
                "REJECTED",
                "EXPIRED",
                "CANCELLED",
                name="tradestatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "proposed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["proposing_team_id"],
            ["teams.id"],
        ),
        sa.ForeignKeyConstraint(
            ["receiving_team_id"],
            ["teams.id"],
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_trade_proposals_session", "trade_proposals", ["session_id"], unique=False)
    op.create_table(
        "waiver_bids",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("team_id", sa.UUID(), nullable=False),
        sa.Column("period_number", sa.Integer(), nullable=False),
        sa.Column("add_player_id", sa.String(length=50), nullable=False),
        sa.Column("drop_player_id", sa.String(length=50), nullable=True),
        sa.Column("bid_amount", sa.Integer(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING", "WON", "LOST", "CANCELLED", name="waiverbidstatus", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_waiver_bids_session_team_period",
        "waiver_bids",
        ["session_id", "team_id", "period_number"],
        unique=False,
    )
    op.create_table(
        "draft_picks",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("draft_id", sa.UUID(), nullable=False),
        sa.Column("team_id", sa.UUID(), nullable=False),
        sa.Column("player_id", sa.String(length=50), nullable=False),
        sa.Column("round", sa.Integer(), nullable=False),
        sa.Column("pick_number", sa.Integer(), nullable=False),
        sa.Column("bid_amount", sa.Integer(), nullable=True),
        sa.Column(
            "picked_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["draft_id"],
            ["drafts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_draft_picks_draft", "draft_picks", ["draft_id"], unique=False)
    op.create_table(
        "trade_locks",
        sa.Column("player_id", sa.String(length=50), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("trade_proposal_id", sa.UUID(), nullable=False),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["trade_proposal_id"],
            ["trade_proposals.id"],
        ),
        sa.PrimaryKeyConstraint("player_id", "session_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("trade_locks")
    op.drop_index("ix_draft_picks_draft", table_name="draft_picks")
    op.drop_table("draft_picks")
    op.drop_index("ix_waiver_bids_session_team_period", table_name="waiver_bids")
    op.drop_table("waiver_bids")
    op.drop_index("ix_trade_proposals_session", table_name="trade_proposals")
    op.drop_table("trade_proposals")
    op.drop_table("standings")
    op.drop_table("session_memberships")
    op.drop_index("ix_roster_players_team", table_name="roster_players")
    op.drop_table("roster_players")
    op.drop_index("ix_player_scores_session_period", table_name="player_scores")
    op.drop_table("player_scores")
    op.drop_index("ix_pending_decisions_session_team", table_name="pending_decisions")
    op.drop_table("pending_decisions")
    op.drop_index("ix_matchups_session_period", table_name="matchups")
    op.drop_table("matchups")
    op.drop_table("drafts")
    op.drop_index("ix_agent_decisions_session_team", table_name="agent_decisions")
    op.drop_table("agent_decisions")
    op.drop_table("teams")
    op.drop_index("ix_snapshots_session_seq", table_name="snapshots")
    op.drop_table("snapshots")
    op.drop_index(op.f("ix_session_invites_token"), table_name="session_invites")
    op.drop_table("session_invites")
    op.drop_index("ix_processed_events_session_seq", table_name="processed_events")
    op.drop_table("processed_events")
    op.drop_table("sessions")
    op.drop_index("ix_season_events_type", table_name="season_events")
    op.drop_index("ix_season_events_script_week", table_name="season_events")
    op.drop_index("ix_season_events_script_seq", table_name="season_events")
    op.drop_table("season_events")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_index(op.f("ix_users_auth0_sub"), table_name="users")
    op.drop_table("users")
    op.drop_table("season_scripts")
    # ### end Alembic commands ###
